//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: FaceTracker.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _FACETRACKER_SOURCE_FACETRACKER_BASE_CLASSES_H
#define _FACETRACKER_SOURCE_FACETRACKER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/toolbar.h>
#include <wx/stattext.h>
#include <wx/choice.h>
#include <wx/arrstr.h>
#include <wx/checkbox.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/imaglist.h>
#include "ocvframe.h"
#include <wx/slider.h>
#include <wx/button.h>
#include <wx/filepicker.h>
#include <wx/textctrl.h>
#include <wx/timer.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class MainFrameBase : public wxFrame
{
protected:
    wxBoxSizer* boxSizer3;
    wxToolBar* m_topToolbar;
    wxStaticText* m_staticText37;
    wxChoice* m_source;
    wxCheckBox* m_writeImage;
    wxCheckBox* m_writeLandmarks;
    wxCheckBox* m_writeBones;
    wxCheckBox* m_singleStepEnable;
    wxNotebook* m_Pages;
    wxPanel* m_panel21;
    wxBoxSizer* MainPageSizer;
    OpenCVFrame* m_Display;
    wxFlexGridSizer* flexGridSizer129;
    wxSlider* m_videoPosition;
    wxButton* m_SingleStep;
    wxButton* m_button133;
    wxPanel* m_panel39;
    wxBoxSizer* boxSizer41;
    wxStaticText* m_staticText79;
    wxFilePickerCtrl* m_nameMap;
    wxFlexGridSizer* flexGridSizer57;
    wxButton* m_button61;
    wxButton* m_button85;
    wxButton* m_button87;
    wxStaticText* m_staticText93;
    wxDirPickerCtrl* m_imageDir;
    wxStaticText* m_staticText119;
    wxFilePickerCtrl* m_restReference;
    wxGridSizer* gridSizer125;
    wxButton* m_button127;
    wxPanel* m_panel113;
    wxBoxSizer* boxSizer115;
    wxTextCtrl* m_actionData;
    wxTimer* m_frameTimer;

protected:
    virtual void onQuit(wxCommandEvent& event) { event.Skip(); }
    virtual void onStart(wxCommandEvent& event) { event.Skip(); }
    virtual void onStop(wxCommandEvent& event) { event.Skip(); }
    virtual void onProperties(wxCommandEvent& event) { event.Skip(); }
    virtual void onRecordStart(wxCommandEvent& event) { event.Skip(); }
    virtual void onRecordStop(wxCommandEvent& event) { event.Skip(); }
    virtual void onWriteImageChange(wxCommandEvent& event) { event.Skip(); }
    virtual void onWriteLandmarks(wxCommandEvent& event) { event.Skip(); }
    virtual void onWriteBones(wxCommandEvent& event) { event.Skip(); }
    virtual void onSingleStep(wxCommandEvent& event) { event.Skip(); }
    virtual void onVideoChanged(wxScrollEvent& event) { event.Skip(); }
    virtual void OnFrameStep(wxCommandEvent& event) { event.Skip(); }
    virtual void onSetRef(wxCommandEvent& event) { event.Skip(); }
    virtual void onFileChanged(wxFileDirPickerEvent& event) { event.Skip(); }
    virtual void onSaveRecords(wxCommandEvent& event) { event.Skip(); }
    virtual void onSaveReduced(wxCommandEvent& event) { event.Skip(); }
    virtual void onSaveRigify(wxCommandEvent& event) { event.Skip(); }
    virtual void onDirNameChange(wxFileDirPickerEvent& event) { event.Skip(); }
    virtual void onSaveReference(wxCommandEvent& event) { event.Skip(); }
    virtual void onTimer(wxTimerEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText37() { return m_staticText37; }
    wxChoice* GetSource() { return m_source; }
    wxCheckBox* GetWriteImage() { return m_writeImage; }
    wxCheckBox* GetWriteLandmarks() { return m_writeLandmarks; }
    wxCheckBox* GetWriteBones() { return m_writeBones; }
    wxCheckBox* GetSingleStepEnable() { return m_singleStepEnable; }
    wxToolBar* GetTopToolbar() { return m_topToolbar; }
    OpenCVFrame* GetDisplay() { return m_Display; }
    wxSlider* GetVideoPosition() { return m_videoPosition; }
    wxButton* GetSingleStep() { return m_SingleStep; }
    wxButton* GetButton133() { return m_button133; }
    wxPanel* GetPanel21() { return m_panel21; }
    wxStaticText* GetStaticText79() { return m_staticText79; }
    wxFilePickerCtrl* GetNameMap() { return m_nameMap; }
    wxButton* GetButton61() { return m_button61; }
    wxButton* GetButton85() { return m_button85; }
    wxButton* GetButton87() { return m_button87; }
    wxStaticText* GetStaticText93() { return m_staticText93; }
    wxDirPickerCtrl* GetImageDir() { return m_imageDir; }
    wxStaticText* GetStaticText119() { return m_staticText119; }
    wxFilePickerCtrl* GetRestReference() { return m_restReference; }
    wxButton* GetButton127() { return m_button127; }
    wxPanel* GetPanel39() { return m_panel39; }
    wxTextCtrl* GetActionData() { return m_actionData; }
    wxPanel* GetPanel113() { return m_panel113; }
    wxNotebook* GetPages() { return m_Pages; }
    wxTimer* GetFrameTimer() { return m_frameTimer; }
    MainFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Face Tracker"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(800, 600), long style = wxDEFAULT_FRAME_STYLE);
    virtual ~MainFrameBase();
};

#endif
